"""Embedding components for seismic SSL clustering."""

from seis_ssl_cluster.embedding.extractor import (
	CURRENT_STUDENT_UNMASKED_EMBEDDING_SEMANTICS,
	REFRESH_EXTRACTION_DESCRIPTOR_NAME,
	EmbeddingExtractionSettings,
	SurveyEmbeddingResult,
	build_embedding_metadata,
	extract_embeddings_from_loaded_model,
	extract_survey_embeddings,
	extraction_settings_from_config,
	reduce_valid_mask_to_tokens,
	run_embedding_extraction,
)
from seis_ssl_cluster.embedding.merge import EmbeddingMerger
from seis_ssl_cluster.embedding.representation_diagnostics import (
	DEFAULT_REPRESENTATION_LAYER_NORM_EPS,
	DEFAULT_REPRESENTATION_SAMPLE_SIZE,
	REPRESENTATION_METRIC_KEYS,
	EmbeddingRepresentationSource,
	build_embedding_representation_diagnostics,
	representation_metrics,
	systematic_valid_token_indices,
	write_embedding_representation_diagnostics,
)
from seis_ssl_cluster.embedding.sliding_window import (
	SlidingWindow,
	compute_stride_xyz,
	iter_sliding_windows,
	padded_volume_shape_xyz,
	token_grid_shape_xyz,
)
from seis_ssl_cluster.embedding.writer import (
	EmbeddingOutputPaths,
	cleanup_temp_outputs,
	commit_staged_outputs,
	create_merge_memmaps,
	file_sha256,
	metadata_matches,
	output_paths,
	prepare_outputs,
	write_metadata,
)
from seis_ssl_cluster.models.amplitude_encoder_factory import (
	build_model_from_checkpoint_payload,
	build_model_from_config,
)

__all__ = [
	'CURRENT_STUDENT_UNMASKED_EMBEDDING_SEMANTICS',
	'DEFAULT_REPRESENTATION_LAYER_NORM_EPS',
	'DEFAULT_REPRESENTATION_SAMPLE_SIZE',
	'REFRESH_EXTRACTION_DESCRIPTOR_NAME',
	'REPRESENTATION_METRIC_KEYS',
	'EmbeddingExtractionSettings',
	'EmbeddingMerger',
	'EmbeddingOutputPaths',
	'EmbeddingRepresentationSource',
	'SlidingWindow',
	'SurveyEmbeddingResult',
	'build_embedding_metadata',
	'build_embedding_representation_diagnostics',
	'build_model_from_checkpoint_payload',
	'build_model_from_config',
	'cleanup_temp_outputs',
	'commit_staged_outputs',
	'compute_stride_xyz',
	'create_merge_memmaps',
	'extract_embeddings_from_loaded_model',
	'extract_survey_embeddings',
	'extraction_settings_from_config',
	'file_sha256',
	'iter_sliding_windows',
	'metadata_matches',
	'output_paths',
	'padded_volume_shape_xyz',
	'prepare_outputs',
	'reduce_valid_mask_to_tokens',
	'representation_metrics',
	'run_embedding_extraction',
	'systematic_valid_token_indices',
	'token_grid_shape_xyz',
	'write_embedding_representation_diagnostics',
	'write_metadata',
]
