"""Migration-validation contracts that keep historical artifacts read-only."""

from seis_ssl_cluster.migration.performance_results import (
	ArtifactReuse,
	CosineSimilaritySummary,
	MetadataDiff,
	MetadataDifference,
	MigrationDecision,
	NumericArrayComparison,
	artifact_identity,
	classify_metadata_diff,
	commit_staged_artifact_directory,
	compare_numeric_arrays,
	cosine_similarity_summary_to_dict,
	decide_migration_status,
	metadata_diff_to_dict,
	migration_decision_to_dict,
	quarantine_artifact,
	reuse_or_quarantine_artifact,
	staged_artifact_directory,
	summarize_rowwise_cosine_similarity,
	validate_completion_manifest,
	write_completion_manifest,
	write_json_atomic,
	write_text_atomic,
)

__all__ = [
	'ArtifactReuse',
	'CosineSimilaritySummary',
	'MetadataDiff',
	'MetadataDifference',
	'MigrationDecision',
	'NumericArrayComparison',
	'artifact_identity',
	'classify_metadata_diff',
	'commit_staged_artifact_directory',
	'compare_numeric_arrays',
	'cosine_similarity_summary_to_dict',
	'decide_migration_status',
	'metadata_diff_to_dict',
	'migration_decision_to_dict',
	'quarantine_artifact',
	'reuse_or_quarantine_artifact',
	'staged_artifact_directory',
	'summarize_rowwise_cosine_similarity',
	'validate_completion_manifest',
	'write_completion_manifest',
	'write_json_atomic',
	'write_text_atomic',
]
